@startuml
'https://plantuml.com/class-diagram

class Deck {
	- Array<Card> cards
	-- Getters --
	+Array<Card> cards()
	+Number count
	-- Methods --
	+ctor(Card)
	+ctor(Array<Card>)
	+ctor()
	+add(Card)
	+Card remove(Card)
	+Card remove()
	+Card remove(index)
	+shuffle()
	+deal(Deck deck)
	+getSuit(String suit)
	+getRank(String rank)
	+getValue(Any value)
	-- Interface Methods --
	+sort()
}


@enduml